const fs=require('node:fs');const vm=require('node:vm');const assert=require('node:assert/strict');const test=require('node:test');
const source=fs.readFileSync(require('node:path').join(__dirname,'../frontend/app.js'),'utf8');
function extract(start,end){return source.slice(source.indexOf(start),source.indexOf(end,source.indexOf(start)));}
const timing=extract('function songTime(s)','async function loadSongsCatalog');
function state(){let pauses=0,plays=0;const audio={currentTime:4,paused:false,ended:false,playbackRate:1,pause(){this.paused=true;pauses++;},play(){this.paused=false;plays++;return Promise.resolve();}};return {sound:true,songAudio:audio,currentSongUrl:'/test.mp3',recording:{},playback:true,console,counts:()=>({pauses,plays})};}
const frame=t=>({mode:'running',speed:1,game:{time:t,song:{audio_url:'/test.mp3',audio_offset:2.4}}});
test('recorded playback never repeatedly seeks the audio to delayed images',()=>{const c=state();vm.createContext(c);vm.runInContext(timing,c);c.s=frame(3);vm.runInContext('syncSongAudio(s)',c);assert.equal(c.songAudio.currentTime,4);});
test('pausing replay pauses music and the count-in stays silent',()=>{const c=state();vm.createContext(c);vm.runInContext(timing,c);c.playback=false;c.s=frame(8);vm.runInContext('syncSongAudio(s)',c);assert.equal(c.songAudio.paused,true);c.playback=true;c.s=frame(1);vm.runInContext('syncSongAudio(s)',c);assert.equal(c.songAudio.currentTime,0);assert.equal(c.songAudio.paused,true);});
test('resume seeks once to the recording timeline with its audio offset',()=>{const c=state();c.songAudio.paused=true;vm.createContext(c);vm.runInContext(timing,c);c.s=frame(12.4);vm.runInContext('syncSongAudio(s)',c);assert.equal(c.songAudio.currentTime,10);assert.equal(c.songAudio.paused,false);});
test('replay frames follow actual audio time rather than drifting wall time',()=>{const render=extract('function render(now)',"fetch('/api/brain')");const c={recording:{frames:Array.from({length:20},(_,i)=>frame(i))},playback:true,replayIndex:0,replayOffset:0,replayStart:0,sound:true,songAudio:{currentTime:2.6,paused:false,ended:false},shown:frame(0),$:()=>({}),display:s=>{c.shown=s;},frameImage:null,stage:null,drawBrain(){},drawSpark(){},requestAnimationFrame(){}};vm.createContext(c);vm.runInContext(render,c);vm.runInContext('render(15000)',c);assert.equal(c.replayIndex,5);assert.equal(c.shown.game.time,5);});
